version: '3.1'
services:
  next-supa-base:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: frontend
    container_name: frontend
    restart: always
    env_file:
      - .env
    networks:
      - kzai-network

  nginx:
    image: nginx:latest
    hostname: loadbalancer
    container_name: loadbalancer
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/kzai.pro/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/kzai.pro/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - /var/www/certbot:/var/www/certbot
    networks:
      - kzai-network

networks:
  kzai-network:
    driver: bridge

