import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>KZAI Presents</h1>
        </header>
        <main>{children}</main>
        <footer>
          <p>© 2024 KZAI Pro App</p>
        </footer>
        </body>
    </html>
  );
}
